import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// app/layout.js

export const metadata = {
  title: {
default: "Direop | Smart Link Solutions for Automation Pros",
    template: 'Direop | %s' // هذا سيجعل أي صفحة تضيف "Dashboard" تصبح "Direop | Dashboard"
  },
description: "The essential link management toolkit for automation experts. Optimize, track, and manage your links seamlessly within your automated workflows. Simple, powerful, and built for scale.",  keywords: ['link management for automation', 'automation tools','TikTok Automation', 'smart links', 'URL optimization', 'Direop'],
  authors: [{ name: 'Direop' }],
  icons: {
    icon: '/favicon.ico',
    // apple: '/apple-touch-icon.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* لا حاجة لوضع head يدوياً، Next.js سيتكفل بالباقي */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
