import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  metadataBase: new URL('https://direop.com'),
  title: {
    default: 'Direop - Copy and Paste Special Characters & Symbols',
    template: '%s | Direop'
  },
  description: 'Quickly copy and paste special characters and symbols, math characters, fancy letters, and emojis. One-click tool for social media and documents.',
  
  // نقلنا الـ icons خارج الـ openGraph لتكون في المستوى الرئيسي
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },

  openGraph: {
    title: 'Direop - Special Characters Tool',
    description: 'The fastest way to special characters copy paste symbols, math characters, fancy letters, and emojis.',
    url: 'https://direop.com',
    siteName: 'Direop',
    locale: 'en_US',
    type: 'website',
    // يفضل دائماً إضافة صورة OG هنا لتظهر عند مشاركة الرابط
    images: [
      {
        url: '/og-image.png', 
        width: 1200,
        height: 630,
        alt: 'Direop - Special Characters Tool',
      },
    ],
  },

  twitter: {
    card: 'summary_large_image',
    title: 'Direop - Copy & Paste special Characters and Symbols',
    description: 'Fast one-click tool for all your symbol needs.',

  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
